version: '3.8'

services:
  telegraf:
    image: docker-upstream.apple.com/telegraf:${TELEGRAF_VERSION}
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - TARGET_HOST=${TARGET_HOST}
    ports:
      - "9273:9273"
    depends_on:
      - prometheus
    networks:
      - sre-net
    dns:
      - 8.8.8.8
      - 8.8.4.4

  prometheus:
    image: docker-upstream.apple.com/prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - sre-net

  grafana:
    image: docker-upstream.apple.com/grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - sre-net

networks:
  sre-net:
    driver: bridge

volumes:
  grafana_data:
